import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";

import { ReactQueryClientProvider } from "@/providers/ReactQueryClientProvider";
import LayoutWrapper from "@/components/layout-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemon App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ReactQueryClientProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ReactQueryClientProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
